language: php
php: "7.2"
services:
- postgresql
before_install:
- psql -c 'create database homestead' -U postgres
- composer self-update
- composer create-project laravel/laravel
- cd ./laravel
- composer config repositories.ikdev github https://github.com/RobyFerro/Laravel-Procedure-Migration.git
- composer require ikdev/procedure_migration
- php artisan vendor:publish --tag=procedure_migration
- php artisan key:generate
script:
- php artisan migrate
- php vendor/phpunit/phpunit/phpunit --configuration vendor/ikdev/procedure_migration/travis.phpunit.xml
